### ISSUE TITLE
non-keyword payloads not supported by sign_serialize

### ISSUE THREAD

**Issue by isysd** [g-p-g/bitjws#2]
The only way to specify the payload for sign_serialize is using keyword arguments. This is fine for dict payloads, but doesn't work for strings, lists, and other "arg" types.

Perhaps an optional 'payload' parameter should be accepted for sign_serialize. If 'payload' is set, then **kwargs are ignored, and the payload is used as is.

**Comment by g-p-g** [comment]
If that is desired, other places need to be modified besides sign_serialize. The decoding also assumes the payload is in JSON. While the JWS spec mentions that the payload doesn't need to be JSON, you can't really use the claims (exp, aud, etc described at http://openid.net/specs/draft-jones-json-web-token-07.html) without using it.

The idea of accepting a payload as is sounds fine, so both multisig_sign and sign could take that. The _deserialize functions would need a new argument to not attempt to decode the payload as JSON.

**Comment by isysd** [comment]
JSON doesn't need to be a dict. Strings and lists are perfectly valid JSON. Examples:

'"JSON string is valid"'

'["one", "two"]'

**Comment by g-p-g** [comment]
Is "123\"" a string? That is not valid JSON.

**Comment by isysd** [comment]
Actually you may be right about strings, but JSON definitely supports lists or arrays. That is what I'm after, primarily. I.e. I'd like to return a list of something as a bitjws signed message.

I see that the JWT does specify that the payload has to be a dict. It seems like I'm after an alternative "typ" altogether.

**Comment by g-p-g** [comment]
I actually mentioned that the JWT spec does /not/ say that the payload must be formatted as JSON. So it's ok to pass an arbitrary payload, as long as the code here is modified to cope with that.

**Comment by g-p-g** [comment]
From the proposed spec (linked in the README file here): "(Note that the payload can be any content and need not be a representation of a JSON object.)"

**Comment by isysd** [comment]
That is JWS. JWS is agnostic, but JWT it seems is not. From the JWT proposed spec:

"As per RFC 4627 [RFC4627] Section 2.2, the JSON object consists of zero or more name/value pairs (or members), where the names are strings and the values are arbitrary JSON values."

http://openid.net/specs/draft-jones-json-web-token-07.html#anchor3

**Comment by g-p-g** [comment]
Well, I guess its possible to interpret it in more than one way. In the same document you mention, Section 7, item 5:

    If the JWT is to be signed, create a JWS using the JWT Header as the JWS Header and the Message as the JWS Payload; all steps specified in [JWS] for creating a JWS MUST be followed. Let the JWT Second Part be the Encoded JWS Payload and let the JWT Third Part be the Encoded JWS Signature.

That paragraph links to https://tools.ietf.org/html/draft-jones-json-web-signature-04. Over there, section "A.1.1.  Encoding" repeats that  the payload can be any base64url encoded content, and need not be a base64url encoded JSON object.

**Comment by isysd** [comment]
I agree the specs seem to be ambiguous. It seems the sections referring to dict structure may have been primarily referring to the header, while the payload may be any format?

JWS seems far more interesting to me, as it has broadly applicable functionality. JWT seems specifically designed for openid, and not particularly useful outside of it. That isn't necessarily a problem, except their specs mix them all together.

In particular, the use case I am working on does not use JWT for it's intended purpose. It attempts to re-use the JWT claims set for passing a message. The "claims set" structure may simply not be adequate for generalized message usage.

**Comment by isysd** [comment]
As discussed offline, it seems the best solution is to add a 'payload' field to the JWT claim set. While it may be possible to send other data types as JWS payloads, it is definitely allows to customize claim sets like this.

GP, [20.10.15 10:53]
alright, so if I understand this right now it's being used like:

GP, [20.10.15 10:53]
bitjws.sign_serialize(somekey, field1=value, field2=value, ...)

GP, [20.10.15 10:53]
and instead we would use it as bitjws.sign_serialize(somekey, payload={field1: value, field2: value, ...})

**Comment by g-p-g** [comment]
I'm closing this on the basis that currently the header forces "typ" to be JWT, and JWT mandates the payload to be JSON encoded.

The first step for making this change seems to be modifying the header generator, so it can take a different type. After that it's not clear how the serialize/deserialize functions will work, maybe it should consider the header "typ" and based on some registered function it would proceed with serialization/deserialization based on that.
